### ISSUE TITLE
Minor prose turn?

### ISSUE THREAD

**Issue by bkardell** [Maps4HTML/HTML-Map-Element-UseCases-Requirements#22]
"""but its basic functionality (to define geometric areas on an image that represent distinct hyperlinks) has not evolved to include what users today consider a standard web map (such as those provided by Google, Bing, or OpenStreetMap"""

Minor prose nit probably but this reads on further reading like it has a slightly oddly specific turn.. would it make sense to say something more specifically  about capability evolution more broadly here? Like.. Defining geometric links over a single image was the common generalized use case and sort of state of things. Today, many of the things that provided those generalized use cases: maps (all kinds, not just strictly geo coord), technical drawings, diagrams, charting and so, on all now include many additional common modern features like the ability to pan and zoom and somehow progressively load and layer these relationships?

**Comment by AmeliaBR** [comment]
What are you suggesting?  Focus on the capabilities instead of referring to a "standard web map" ? Maybe:

> …has not evolved to include ***many capabilities*** that users today expect when interacting with maps on the web, such as the ability to dynamically change the map view.

**Comment by bkardell** [comment]
Yup, exactly like that. This is why you are an editor. 😄

**Comment by prushforth** [comment]
Part of the reason _geospatial_ maps are important is because they have a
very mature community, which may not be the case for other forms of map,
and I would really like to be able to attract contributions to the relevant
Web standards from the Web mapping and Web map standards community, in
particular.  That's not to discount the importance of non-geospatial maps,
just that interest and contributions may be more forthcoming if the
geospatial community in particular can see what's in it for them.
